# FlickerSoon Configuration
#############################
#                           #
# Update this section       #
#                           #
#############################
[Apis]
OmdbApiKey = "ec2ae74" # Insert your OMDb API here
TmdbApiKey = "" # Insert your TMDb API here

##############################
#                            #
# Leave this section unless  #
# you know what you're doing #
#                            #
##############################

[Endpoints]
OmdbEndpoint = "http://www.omdbapi.com/?apikey=" # Insert your OMDb endpoint here
TmdbEndpoint = "" # Insert your TMDb endpoint here

